#!/bin/bash

if [ -f /etc/firstboot ]; then
	mv /etc/firstboot /etc/firstboot-bak
	cd /boot
	rm -f *.old *4.19.282*
	sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT/c\GRUB_CMDLINE_LINUX_DEFAULT="ro console=tty0 console=ttyS0,115200n8 nokaslr debug earlyprintk=ttyS0 net.ifnames=0 biosdevname=0 kgdboc=ttyS0,115200 kgdbwait initcall_debug log_buf_len=32M serial8250.poll_timeout=10   level=10 console=ttyS0 apparmor=0 nokaslr debug earlyprintk=ttyS0 net.ifnames=0 biosdevname=0 kgdboc=ttyS0,115200 kgdbwait initcall_debug log_buf_len=32M serial8250.poll_timeout=10 "' /etc/default/grub
	sed -i '/^GRUB_HIDDEN/d' /etc/default/grub
	sed -i 's/GRUB_TIMEOUT=10/GRUB_TIMEOUT=20/g' /etc/default/grub
	sed -i 's/GRUB_DEFAULT=0/GRUB_DEFAULT=2/g' /etc/default/grub
	update-initramfs -c -k 4.15.18-kdev
	update-grub2
	sync

	if which chpasswd &> /dev/null ; then
		echo root:linux | chpasswd
	elif which passwd &> /dev/null ; then
		echo linux | passwd -stdin root
	else
		echo "can't reset root passwd"
	fi
	sync
	reboot -f
fi

dhclient

exit 0

